language: php

php:
  - 7.1
  - 7.2

sudo: required

addons:
   chrome: stable

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

services:
  - xvfb

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist
  - composer config --list --global
  - export DISPLAY=:99.0
  - ./sandbox_setup.sh
  - cd sandbox; ./vendor/laravel/dusk/bin/chromedriver-linux &
  - php artisan dusk:install
  - php artisan serve --env=dusk.local &

script:
  - cd sandbox ; php artisan dusk ; cd ..
  - cd sandbox ; php artisan adminlte:admin ; ./vendor/bin/phpunit --coverage-text --coverage-clover=../coverage.clover ; cd ..
  - vendor/bin/phpcs -p --standard=PSR2.xml --runtime-set ignore_errors_on_exit 1 --runtime-set ignore_warnings_on_exit 1 src tests

after_script:
  - ./sandbox_destroy.sh
  - |
      if [[ "$TRAVIS_PHP_VERSION" != 'hhvm' && "$TRAVIS_PHP_VERSION" != '7.0' ]]; then
        wget https://scrutinizer-ci.com/ocular.phar
        php ocular.phar code-coverage:upload --format=php-clover coverage.clover
      fi
